name: mikesir87's blog

description: Posts from Michael Irwin

links:
  dribbble:
  email:
  facebook:
  flickr:
  github: mikesir87 
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: mikesir87
  stackoverflow: users/502139/mikesir87 
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: +MichaelIrwin


disqus: mikesir87blog

google_analytics: UA-9453218-25

url: http://blog.mikesir87.io

baseurl: ""

permalink: /:year/:month/:title/
excerpt_separator: <!--more-->

version: v1.1.0

sass:
  style: :compressed # You might prefer to minify using :compressed
plugins:
  - jekyll-feed
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
feed:
  path: atom.xml
