version: '2'

services:
  app:
    image: jekyll/jekyll
    command: bash -c "gem install bundler:1.16.1 && bundle install && jekyll serve --future --drafts"
    volumes:
      - ./:/srv/jekyll:cached
    ports:
      - 4000:4000
